alias maj='sudo apt-get update && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y'
alias kodi='ssh crampi@192.168.0.14'
alias owncloud='ssh pi@192.168.0.17'
alias tor='cd /home/crampi/Téléchargements/tor-browser_fr/ && ./start-tor-browser.desktop'
alias vps='ssh -l crampi -p 1022 vps190615.ovh.net'
